"""
interrupt_before / interrupt_after: Pausing a Graph (Interactive Terminal Interrupt)
=====================================================================================
`compile(interrupt_before=[...])` / `interrupt_after=[...]` tell
LangGraph to pause execution right before (or after) specific named
nodes run, returning control to the caller instead of continuing.

In this script, control returns to the main Python script when paused,
where we prompt the human for real terminal input using `input()`.
"""

from typing import TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver


class State(TypedDict):
    draft: str
    approved: bool
    published: str


def write_draft(state: State) -> dict:
    return {"draft": "Quarterly earnings look strong."}


def publish(state: State) -> dict:
    if not state.get("approved"):
        return {"published": "REJECTED: Draft was not approved by human reviewer."}
    return {"published": f"PUBLISHED: {state['draft']}"}


builder = StateGraph(State)
builder.add_node("write_draft", write_draft)
builder.add_node("publish", publish)
builder.add_edge(START, "write_draft")
builder.add_edge("write_draft", "publish")
builder.add_edge("publish", END)

# Pause right before `publish` runs, so a human can review the draft first.
graph = builder.compile(checkpointer=MemorySaver(), interrupt_before=["publish"])

config = {"configurable": {"thread_id": "post-1"}}

print("=== 1. Invoking Graph (Runs until interrupt) ===")
result = graph.invoke({"draft": "", "approved": False, "published": ""}, config=config)

# Execution stopped before `publish`. Inspect state snapshot.
snapshot = graph.get_state(config)
print(f"\n[INTERRUPT DETECTED] Next scheduled node: {snapshot.next}")
current_draft = snapshot.values.get("draft")
print(f"Current Draft generated by graph: \"{current_draft}\"")

# --- REAL TERMINAL INTERRUPT ---
print("\n--- HUMAN IN THE LOOP TERMINAL REVIEW ---")
user_input = input("Action [(a)pprove / (e)dit / (r)eject]: ").strip().lower()

if user_input in ["a", "approve", "yes"]:
    graph.update_state(config, {"approved": True})
    print("-> Human action: Approved draft.")
elif user_input in ["e", "edit"]:
    new_draft = input("Enter new draft text: ").strip()
    graph.update_state(config, {"draft": new_draft, "approved": True})
    print(f"-> Human action: Updated draft to \"{new_draft}\".")
else:
    graph.update_state(config, {"approved": False})
    print("-> Human action: Rejected draft.")

print("\n=== 2. Resuming Graph Execution ===")
# A human reviews and updates state, then resumes by invoking with input=None.
final = graph.invoke(None, config=config)
print(f"Final State Result: {final['published']}")

