"""
InjectedToolArg and Returning Artifacts from Tools
=====================================================
- InjectedToolArg: marks a tool parameter that should NOT be exposed to the
  LLM's tool schema — instead it's injected by your own code at call time
  (e.g. a user_id, a db connection, or state pulled from LangGraph). This
  keeps sensitive/internal args out of what the model sees and can hallucinate.
- Artifacts: a tool can return two things — a lightweight string for the model
  (`content`) and a rich object for your application (`artifact`), e.g. a
  full dataframe, an image, or raw API payload the LLM never needs to read.
"""

from typing import Annotated
from langchain_core.tools import tool, InjectedToolArg


@tool
def get_user_orders(user_id: Annotated[str, InjectedToolArg], status: str) -> str:
    """Get a user's orders filtered by status (e.g. 'pending', 'shipped')."""
    # user_id is injected by our code, never generated by the LLM.
    return f"Orders for {user_id} with status={status}: [order_1, order_2]"


# The LLM only ever sees `status` in the tool schema — user_id is hidden.
print(get_user_orders.args)
# -> {'status': {'title': 'Status', 'type': 'string'}}

# We inject the real value ourselves before invoking:
result = get_user_orders.invoke({"status": "pending", "user_id": "u_42"})
print(result)


# --- Returning artifacts (content for the LLM, artifact for your app) ---
@tool(response_format="content_and_artifact")
def run_sql_query(query: str) -> tuple[str, dict]:
    """Run a SQL query and return a short summary plus the full result set."""
    full_result = {"rows": [{"id": 1, "name": "Ada"}, {"id": 2, "name": "Lin"}]}
    summary = f"Query returned {len(full_result['rows'])} rows."
    return summary, full_result  # (content, artifact)


tool_message = run_sql_query.invoke(
    {"name": "run_sql_query", "args": {"query": "SELECT * FROM users"}, "id": "call_1", "type": "tool_call"}
)
print(tool_message.content)   # -> short summary, shown to the LLM
print(tool_message.artifact)  # -> full dict, used by your app code / UI, not sent to the LLM
