"""
CREATE_STUFF_DOCUMENTS_CHAIN AND CREATE_RETRIEVAL_CHAIN
===========================================================
These two functions are the modern (LCEL-based) replacement for RetrievalQA.
Instead of a monolithic legacy Chain class, you compose small Runnables:

- create_stuff_documents_chain: takes an LLM + a prompt (which must include a
  {context} placeholder) and returns a Runnable that "stuffs" a list of
  Documents into that placeholder before calling the LLM.

- create_retrieval_chain: wraps a retriever + a "combine documents" chain
  (like the one above) into a single Runnable that takes a user question,
  retrieves docs, and passes them into the combine step, returning both the
  answer and the retrieved context.
"""

from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document
from langchain_ollama import ChatOllama, OllamaEmbeddings
from langchain_community.vectorstores import Chroma

llm = ChatOllama(model="qwen2.5:1.5b", temperature=0)
embeddings = OllamaEmbeddings(model="qwen3-embedding:8b")

# Index mock documents in-memory so the script is runnable
print("Indexing sample documents...")
docs = [
    Document(
        page_content="Our company's refund policy allows refunds within 30 days of purchase for unused items in original packaging. International orders are eligible, but return shipping fees are non-refundable.",
        metadata={"source": "policies/refunds.md"},
    ),
    Document(
        page_content="We offer standard shipping (3-5 business days) and expedited shipping (1-2 business days). All orders over $50 qualify for free standard shipping.",
        metadata={"source": "policies/shipping.md"},
    ),
]
vectorstore = Chroma.from_documents(docs, embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 2})
# --- 1. Define the Prompt Template ---
# The prompt MUST contain a {context} variable.
# create_stuff_documents_chain will scan the prompt for the `{context}` key and inject
# the concatenated contents of the retrieved documents there.
# It also expects the `{input}` variable for the user's question.
qa_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "Answer the question using only the context below.\n\n{context}"),
        ("human", "{input}"),
    ]
)

# --- 2. Create the Document Combination Chain ---
# create_stuff_documents_chain creates a Runnable chain.
# - Input dictionary: Requires `{"context": List[Document], "input": str}` (plus any other prompt variables).
# - Output: Returns a simple string containing the generated response from the LLM.
# It "stuffs" all documents by joining their content with newlines and placing them in the `{context}` slot.
combine_docs_chain = create_stuff_documents_chain(llm, qa_prompt)

# --- 3. Create the Main Retrieval Chain ---
# create_retrieval_chain wraps the retriever and the document combination chain.
# - Input dictionary: Only requires `{"input": str}` (the user's question).
# - Execution Flow:
#   1. Takes the user's question (`"input"`).
#   2. Queries the retriever to fetch relevant documents.
#   3. Passes the retrieved documents under the key `"context"` along with the original `"input"`
#      to `combine_docs_chain`.
#   4. Returns a complete dictionary containing:
#      - `"input"`: The original query string.
#      - `"context"`: The list of raw retrieved `Document` objects (useful for showing source citations).
#      - `"answer"`: The final text response generated by the LLM.
retrieval_chain = create_retrieval_chain(retriever, combine_docs_chain)

# --- 4. Invoke the Retrieval Chain ---
print("\n--- Running Retrieval Chain ---")
response = retrieval_chain.invoke({"input": "What is our company's refund policy?"})
print("Answer:", response["answer"])
print("Sources used:", [doc.metadata.get("source") for doc in response["context"]])

# --- 5. Streaming Responses Chunk-by-Chunk ---
# Since both chains are built using LCEL (LangChain Expression Language), they inherit the
# Runnable interface, which supports native streaming (`.stream()`) out of the box.
# When streaming, the retrieval chain yields partial dictionaries.
# - The first chunk(s) will contain the retrieved `"context"` list.
# - Subsequent chunks contain increments of the generated text inside the `"answer"` key (e.g., `{"answer": "..."}`).
print("\n--- Streaming Response ---")
for chunk in retrieval_chain.stream({"input": "Summarize the shipping policy."}):
    # Check if the current streamed chunk contains a piece of the generated answer
    if "answer" in chunk:
        print(chunk["answer"], end="", flush=True)
print()
