"""
PRODUCTION EXAMPLE: A Runnable pipeline with real streaming
=============================================================
This shows RunnableLambda used for pre/post-processing around a real LLM,
combined using LCEL (|), with proper streaming and error handling.
"""

from langchain_core.runnables import RunnableLambda, RunnableConfig
from langchain_core.output_parsers import StrOutputParser
from langchain_community.chat_models import ChatOllama


# --- Custom Runnable: input pre-processor ---
def clean_input(text: str) -> str:
    """Trim whitespace and enforce a minimum length before hitting the LLM."""
    text = text.strip()
    if len(text) < 3:
        raise ValueError("Input too short — must be at least 3 characters.")
    return text


# --- Custom Runnable: output post-processor ---
def add_signature(text: str) -> str:
    """Append a signature after the LLM responds."""
    return f"{text}\n\n— Generated by AI Assistant"


preprocessor = RunnableLambda(clean_input)
postprocessor = RunnableLambda(add_signature)

model = ChatOllama(model="qwen2.5:1.5b", temperature=0.7)
parser = StrOutputParser()

# LCEL chain: every piece here is a Runnable, snapped together with |
chain = preprocessor | model | parser | postprocessor


def run_safely(user_input: str):
    """invoke() wrapped with error handling — the production-safe way."""
    try:
        result = chain.invoke(user_input)
        return result
    except ValueError as e:
        return f"Input error: {e}"
    except Exception as e:
        # Catches API failures, rate limits, timeouts, etc.
        return f"Something went wrong calling the model: {e}"


def run_streamed(user_input: str):
    """Real streaming — this time the LLM actually emits token-by-token chunks."""
    cleaned = clean_input(user_input)  # pre-process before entering the streamed part
    for chunk in model.stream(cleaned):
        print(chunk.content, end="", flush=True)  # live "typing" effect
    print()


def run_batch(user_inputs: list[str]):
    """Batch multiple user questions in parallel — much faster than a for-loop."""
    return chain.batch(user_inputs)


if __name__ == "__main__":
    print(run_safely("Tell me a fun fact about the ocean"))
    print(run_safely("hi"))  # triggers the ValueError path, since len < 3... wait "hi" is 2 chars
    run_streamed("Explain gravity in one sentence")

    print(run_batch(["What is Python?", "What is LangChain?"]))